In [14]:
import pandas as pd
corpus_csv = pd.read_csv('../data/corpus.csv', sep='|', engine='python', index_col = 'id')  # Или sep='\t' для TSV

In [15]:
corpus_csv

,Unnamed: 0,src,text
id,,,
c2c64535b0544e6eafcd1a5af55dcae3,0,suicid_forum_topic,"я не знаю, что с этим делать. у меня чувство, ..."
7b15911797ce4cd0a65cbe4e2c172b78,1,suicid_forum_topic,Отправляли ли вас в психиатрическую больницу п...
77dea68b1f90435584821f5fca81a602,2,suicid_forum_topic,"Не зря я назвался тем ником который есть, пото..."
c31e4cf8cb8a4d35913b8bb53c13db55,3,suicid_forum_topic,С поступлением в шарагу я обзавелся тревожным ...
026cb9b359b4475c846391b7ca288a5f,4,suicid_forum_topic,"Мне 26 лет, время от времени хочу умереть, одн..."
...,...,...,...
6835b0b611dd4370b335ca75ef89124d,130560,suicide_helping_forums,привет всем! Меня зовут ярик. Мне 18 лет. Моря...
0d45e6bb90a84a57afb570434ae698e1,130561,suicide_helping_forums,"Я недостоин женщины - моей жены, матери моих д..."
ee1e2b4a316a41c8ac1fae9286a8676f,130562,suicide_helping_forums,"Люди добрые, помогите как-нибуть: я не знаю, ч..."
c06c984b8f9d47b5993661f98df1e07c,130563,suicide_helping_forums,"Добрый вечер. я думаю о самоубийстве, последне..."
93b7300d999242dfb5025190111479b9,130564,suicide_helping_forums,Уже писала свою историю 29.06 на сайте: ______...

In [17]:
corpus_csv = corpus_csv.reset_index().drop(columns=['id', 'Unnamed: 0'])

In [21]:
corpus_csv.sample(10)

,src,text
69111,raw_twitter,надеюсь я еще могу вернуться обратно в свой по...
115799,suicide_helping_forums,"В этом году,я как и большинство моих сверстник..."
118276,suicide_helping_forums,"Здравствуйте. Меня зовут Женя, мне 17 лет. Я д..."
23559,vk,"Здравствуйте, я совсем невменяема, руки трясут..."
75421,raw_twitter,у меня даже мама его узнает уже и когда видит ...
59818,presuicidal,оно того не стоило
50657,presuicidal,"знаете что я решил, что летом буду бегать скри..."
69840,raw_twitter,NaN
120545,suicide_helping_forums,"Так жить не хочется,просто ужас,учусь на врача..."
49743,presuicidal,пиздец хочу поступить в онлайн универ но так г...

In [22]:
corpus_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 130565 entries, 0 to 130564
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   src     130565 non-null  str
 1   text    129116 non-null  str
dtypes: str(2)
memory usage: 142.3 MB

In [26]:
corpus_csv.isna().mean()
corpus_csv = corpus_csv.dropna()

In [27]:
corpus_csv['text'].str.len().describe()

count    129116.000000
mean        632.368328
std        1101.323940
min           1.000000
25%          60.000000
50%         181.000000
75%         793.000000
max       40268.000000
Name: text, dtype: float64

In [29]:
corpus_csv['text'] = corpus_csv['text'].str.strip()

In [31]:
corpus_csv['text'].sample(10)

37462     по-моему прокуратура отсосала на вчерашнем кон...
107210    Здравствуйте. Мне 14 лет, моя мама недавно узн...
111298    Мне нужна помощь. Я не хочу жить.Здравствуйте....
53214     когда-нибудь гетеро парни перестанут писать мн...
55073     1. 2/14 750/750 сожжено 140 мороженое 254 соси...
20240     Не знаю почему решил написать сюда. Идти больш...
123277    Здравствуйте.Я не знаю куда еще мне обратиться...
73023             сбывается мой главный страх. одиночество.
84736     сказал человек, запланировавший перебрать книж...
6016      Здравствуйте. С детства росла без отца с брато...
Name: text, dtype: str

In [32]:
mask = (corpus_csv['text'].str.len().between(200,500))
mask

0         False
1         False
2         False
3         False
4         False
          ...
130560    False
130561    False
130562    False
130563     True
130564    False
Name: text, Length: 129116, dtype: bool

In [33]:
texts_200_500 = corpus_csv.loc[mask, 'text']

In [35]:
texts_200_500.str.len().describe()

count    19460.000000
mean       313.195272
std         84.562988
min        200.000000
25%        247.000000
50%        280.000000
75%        378.000000
max        500.000000
Name: text, dtype: float64

In [36]:
texts_200_500.info()

<class 'pandas.Series'>
Index: 19460 entries, 40 to 130563
Series name: text
Non-Null Count  Dtype
--------------  -----
19460 non-null  str
dtypes: str(1)
memory usage: 10.5 MB

In [38]:
texts_200_500.to_csv('../data/texts_200_500_symbols.csv')

In [39]:
texts_200_500

40        Вот как и многие тут мечусь между жизнью и сме...
48        Я устала от жестокости мира, от глупости и жад...
55        Здравствуйте, эта тема и это сообщения ничто. ...
74        мне планируют платить пенсию 130 евро в месяц....
81        У меня букет психических расстройств, всю свою...
                                ...
130499    Изменила мужу. Не смогла ему признаться, но и ...
130501    не знаю стоит ли писать. в общем четыре месяца...
130506    Много чего есть рассказать. Коротко. Очень сло...
130532    я просто схожу с ума.в такие моменты хочется и...
130563    Добрый вечер. я думаю о самоубийстве, последне...
Name: text, Length: 19460, dtype: str

In [29]:
import json
res_texts = []
with open('../synthesizer_agent/outputs/synthesized_pii.jsonl', 'r') as f:
    for line in f:
        res_texts.append(json.loads(line))
print(res_texts[0])

{'text': 'Я учусь в школе. Есть несколько друзей. Там. И лучшая подруга. Ну как лучшая. Для меня лучшая. Насчет ее отношения ко мне не знаю. Но я очень ценю наше общение. Каждая прогулка с ней для меня как праздник. Но, увы, это бывает не часто. Чаще она гуляет с нашими одноклассниками. А влиться в их компанию нн получается. Ну не принимают они меня.\n\nЯ даже пытался написать ей в телеграм <TELEGRAM>https://t.me/maria_ivanova_7017</TELEGRAM>, но она так и не ответила. Может, я что-то не так сделал? Или она просто не хочет общаться? Не знаю. Если кто-то из вас её увидит, скажите, что я пытался связаться. Или пусть она сама напишет мне на номер <PHONE_NUMBER>+7 (921) 999-44-66</PHONE_NUMBER>. Мне бы хотя бы понять, в чём дело.', 'logic_of_entry': 'Автор делится своими переживаниями о сложностях в общении с одноклассниками и лучшей подругой. В конце текста он может естественно перейти к мысли о том, что пытался наладить контакт через социальные сети или другие каналы связи, но это не помогло. Это позволит вплести данные о телеграмме и номере телефона как попытку связаться или быть на связи.', 'used_entities': [{'key': 'TELEGRAM', 'value': 'https://t.me/maria_ivanova_7017', 'insertion_hint': 'автор упоминает, что пытался связаться с подругой через телеграм, но ответов не было'}, {'key': 'PHONE_NUMBER', 'value': '+7 (921) 999-44-66', 'insertion_hint': 'автор оставляет свой номер телефона как последний способ связаться с ней'}], 'source_fragment': 'Я учусь в школе. Есть несколько друзей. Там. И лучшая подруга. Ну как лучшая. Для меня лучшая. Насчет ее отношения ко мне не знаю. Но я очень ценю наше общение. Каждая прогулка с ней для меня как праздник. Но, увы, это бывает не часто. Чаще она гуляет с нашими одноклассниками. А влиться в их компанию нн получается. Ну не принимают они меня.', 'position_hint': 'Постарайся органично вставить данные в конце текста (как естественное завершение мысли).'}

In [30]:
with open("../synthesizer_agent/outputs/examples_preview.md", "w", encoding="utf-8") as f:
    for i, item in enumerate(res_texts):
        print(
        f'''
        {'-'*100}\n
        EXAMPLE NUMBER {i+1}:\n
        TEXT:\n
        {item['text']}\n
        \n
        LOGIC OF ENTRY:\n
        {item['logic_of_entry']}\n
        \n
        USED ENTITIES:\n
        {item['used_entities']}\n
        \n
        POSITION HINT:\n
        {item['position_hint']}\n
        \n
        SOURCE FRAGMENT:\n
        {item['source_fragment']}
        ''',
        file = f
        )